DROP TABLE account;
CREATE TABLE  IF NOT EXISTS account(
id INT AUTO_INCREMENT PRIMARY KEY COMMENT '账户编号',
username VARCHAR(20) COMMENT '姓名',
cardno VARCHAR(20) UNIQUE COMMENT '银行卡号',
pwd VARCHAR(10)  COMMENT '密码',
balance DOUBLE  COMMENT '余额'
)COMMENT '银行信息表' ENGINE = INNODB CHARSET =utf8;
